name: Build LSPosed Module

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.4

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/configuration-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Generate Gradle Wrapper and Build
      run: |
        gradle wrapper --gradle-version 8.4
        chmod +x ./gradlew
        ./gradlew build
        ./gradlew assembleRelease

    - name: Find APK files
      run: |
        echo "Looking for APK files..."
        find . -name "*.apk" -type f
        echo "Checking app/build/outputs/apk/ directory..."
        ls -la app/build/outputs/apk/ || echo "Directory not found"
        echo "Checking app/build/outputs/ directory..."
        ls -la app/build/outputs/ || echo "Directory not found"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: soul-strike-floating-menu
        path: app/build/outputs/apk/**/*.apk
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      continue-on-error: true
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/**/*.apk
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          ## Soul Strike Floating Menu Module
          
          LSPosed module that adds a floating menu to Soul Strike game.
          
          ### Installation:
          1. Install LSPosed framework
          2. Install this APK
          3. Enable the module in LSPosed
          4. Select Soul Strike as scope
          5. Reboot your device
          6. Launch Soul Strike - floating menu will appear automatically
          
          ### Features:
          - Floating window menu that appears in Soul Strike
          - Expandable/collapsible interface
          - Multiple feature buttons
          - Easy to use and configure
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release Status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Build completed successfully!"
          echo "📱 APK files are available in the artifacts section"
          echo "⚠️  GitHub release creation may have failed due to permissions"
          echo "💡 You can manually create a release and upload the APK from the artifacts"
        else
          echo "❌ Build failed"
        fi
